In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("production_analysis_dataset.csv")
df

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   production_id           50 non-null     int64
 1   product_category        50 non-null     object
 2   factory                 50 non-null     object
 3   shift                   50 non-null     object
 4   supervisor              50 non-null     object
 5   units_produced          50 non-null     int64
 6   defective_units         50 non-null     int64
 7   production_time_hr      50 non-null     float64
 8   machine_downtime_hr     50 non-null     float64
 9   energy_consumption_kwh  50 non-null     int64
 10  profit                  50 non-null     int64
dtypes: float64(2), int64(5), object(4)
memory usage: 4.4+ KB

# Q1. Find the total units produced by each product_category.

In [8]:
df.groupby('product_category')['units_produced'].sum()

product_category
Automotive     9408
Electronics    7491
Furniture      7251
Name: units_produced, dtype: int64

# Q2. Calculate the average profit for each factory.

In [10]:
df.groupby('factory')['profit'].mean().round(2)

factory
Plant_A    18044.38
Plant_B    16973.38
Plant_C    18086.08
Name: profit, dtype: float64

# Q3. Find the total defective_units for each shift.

In [11]:
df.groupby('shift')["defective_units"].sum()

shift
Evening    132
Morning    472
Night      471
Name: defective_units, dtype: int64

# Q4. Calculate the average production_time_hr for each supervisor.

In [12]:
df.groupby('supervisor')['production_time_hr'].mean().round(2)

supervisor
S1    7.80
S2    7.45
S3    7.88
S4    7.96
Name: production_time_hr, dtype: float64

# Q5. Find the total energy_consumption_kwh for each factory and shift.

In [14]:
df.groupby(['factory','shift'])['energy_consumption_kwh'].sum()

factory  shift
Plant_A  Evening     3330
         Morning    11144
         Night      12913
Plant_B  Evening     2889
         Morning     7923
         Night       4981
Plant_C  Evening     2214
         Morning     5632
         Night       7363
Name: energy_consumption_kwh, dtype: int64

# Q6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.

In [15]:
df.groupby('product_category').agg({
    "units_produced":'sum',
    "profit":'mean',
    "defective_units":'max'
})

                  units_produced        profit  defective_units
product_category
Automotive                  9408  18374.722222               34
Electronics                 7491  16945.750000               40
Furniture                   7251  17935.062500               39

# Q7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.

In [16]:
df.groupby('factory').agg({
    "production_time_hr":'mean',
    "machine_downtime_hr":'median'
})

         production_time_hr  machine_downtime_hr
factory
Plant_A            7.890000                0.945
Plant_B            7.579231                1.070
Plant_C            7.810769                0.850

# Q8. For each shift, compute:
minimum profit
maximum profit
average units_produced.

In [17]:
df.groupby('shift').agg({
    "profit":["min","max"],
    "units_produced":"mean"
})

        profit        units_produced
           min    max           mean
shift
Evening  10009  22302     524.857143
Morning  10722  24358     482.090909
Night    12045  24586     470.000000

# Q9. For each supervisor, calculate:
total units_produced
total defective_units.

In [18]:
df.groupby('supervisor').agg({
    "units_produced":'sum',
    "defective_units":'sum'
})

            units_produced  defective_units
supervisor
S1                    5231              209
S2                    6069              264
S3                    7418              273
S4                    5432              329

# Q10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced

In [20]:
df['defectRate']=df.apply(
    lambda x:x['defective_units']/x['units_produced'],axis=1
)
df.head()

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defectRate
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118

# Q11. Using groupby().apply(), find the profit range (max − min) for each factory.

In [21]:
df.groupby('factory').apply(lambda x:x['profit'].max()-x['profit'].min())

factory
Plant_A    14199
Plant_B    14349
Plant_C    12745
dtype: int64

# Q12. Using groupby().apply(), find the row with maximum units_produced in each product_category.

In [26]:
df.groupby('product_category').apply(lambda x:x['units_produced'].max())

product_category
Automotive     690
Electronics    666
Furniture      618
dtype: int64

# Q13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr

# Q14. Find how many times each product_category appears in the dataset.

# Q15. Count the number of records for each shift.

# Q16. Find the most frequent supervisor using value_counts().

# Q17. Sort the dataset by profit in descending order.

# Q18. Sort the dataset by:
•	product_category ascending
•	units_produced descending